erqewr
erqe

diff --git a/.github/workflows/clair.yml b/.github/workflows/clair.yml
--- a/.github/workflows/clair.yml
+++ b/.github/workflows/clair.yml
@@ -33,6 +33,10 @@ jobs:
           curl -L -o docker-scout.tar.gz https://github.com/docker/scout-cli/releases/download/v0.7.0/docker-scout-linux-amd64-0.7.0.tar.gz
           # Check if the file is downloaded correctly
           ls -lh docker-scout.tar.gz
+          if [ $(stat -c %s docker-scout.tar.gz) -lt 100 ]; then
+            echo "Error: The downloaded file is too small. Check the URL."
+            exit 1
+          fi
           # Extract the tar.gz file
           tar -xzvf docker-scout.tar.gz
           # Move docker-scout binary to /usr/local/bin for global use
